# Generated by Django 2.2.1 on 2019-05-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_product_specific_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
